spring:
  datasource:
    hikari:
      auto-commit: true
      cachePrepStmts: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      connection-timeout: 90000
      elideSetAutoCommits: true
      idle-timeout: 110000
      maintainTimeStats: false
      max-lifetime: 120000
      maximum-pool-size: 200
      minimum-idle: 0
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      rewriteBatchedStatements: true
      useLocalSessionState: true
      useServerPrepStmts: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false
storage:
  bucket: informed-racing