draw-change-date:
  uk: 2011-03-30
  ire: 2011-04-11
spring:
  datasource:
    hikari:
      auto-commit: true
      cachePrepStmts: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      connection-timeout: 90000
      elideSetAutoCommits: true
      idle-timeout: 110000
      maintainTimeStats: false
      max-lifetime: 120000
      maximum-pool-size: 10
      minimum-idle: 0
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      rewriteBatchedStatements: true
      useLocalSessionState: true
      useServerPrepStmts: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        event.merge.entity_copy_observer: allow
storage:
  bucket: informed-racing